services:

  login:
    build: ../../services/login
    container_name: LOGIN_SERVICE
    ports:
      - "3000:3000"
    volumes:
      - ../../services/login:/app
      - /app/node_modules
    networks:
      - service
  devices:
    build: ../../services/devices
    container_name: DEVICES_SERVICE
    ports:
      - "3001:3000"
    volumes:
      - ../../services/devices:/app
    networks:
      - service
  places:
    build: ../../services/devices
    container_name: PLACES_SERVICE
    ports:
      - "3002:3000"
    volumes:
      - ../../services/places:/app
    networks:
      - service


networks:
  service:
    driver: bridge