services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EXAMEN
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped